### ISSUE TITLE
file .env

### ISSUE THREAD

**Issue by dat0825** [philnash/twilio-video-react-hooks#1]
How can i get TWILIO_CHAT_SERVICE_SID,TWILIO_TWIML_APP_SID and TWILIO_ALLOW_INCOMING_CALLS?

**Comment by philnash** [comment]
You actually don't need those env variables to run this project. I should have removed them from the file, sorry! Will do that now.

They are for [Twilio Chat](https://www.twilio.com/docs/chat/javascript/quickstart) and [Twilio Client (for making calls in the browser)](https://www.twilio.com/docs/voice/client/javascript) which is why they are not needed for this application.
