### ISSUE TITLE
audio and video track are not enabled and disabled.

### ISSUE THREAD

**Issue by MilanRgm** [philnash/twilio-video-react-hooks#14]
I have implemented the code for mute/unmute for audio and enable/disable for video. But they are not working. When i mute the audio on both end(both browser), I can still hear echo. While disabling the video I can still see video on another end. 

In short here is the code for audio and video 

```javascript
const handleAudioToggle = () => {
    room.localParticipant.audioTracks.forEach(track => {
      if (track.track.isEnabled) {
        track.track.disable();
      } else {
        track.track.enable();
      }
      setToggleAudio(!track.track.isEnabled);
    });
  };

  const handleVideoToggle = () => {
    room.localParticipant.videoTracks.forEach(track => {
      if (track.track.isEnabled) {
        track.track.disable();
      } else {
        track.track.enable();
      }
      setToggleVideo(!track.track.isEnabled);
    });
  };

```

Here is the code for overall reference

```javascript
const Index = ({ roomName, history }) => {
  const [room, setRoom] = React.useState(null);
  const [participants, setParticipants] = React.useState([]);
  const [toggleAudio, setToggleAudio] = React.useState(false);
  const [toggleVideo, setToggleVideo] = React.useState(false);
  const token = localStorage.getItem("token");
  const roomToJoin = roomName || localStorage.getItem("room");

  React.useEffect(() => {
    const participantConnected = participant => {
      setParticipants(prevParticipants => [...prevParticipants, participant]);
    };

    const participantDisconnected = participant => {
      setParticipants(prevParticipants =>
        prevParticipants.filter(p => p !== participant)
      );
    };

    const reconnectingUser = reconnection => {
      console.log("reconnectingUser", reconnection);
    };

    const reconnectedUser = reconnection => {
      console.log("reconnectedUser", reconnection);
    };

      Video.connect(token, {
        name: roomToJoin
      }).then(room => {
        setRoom(room);
        room.on("participantConnected", participantConnected);
        room.on("participantDisconnected", participantDisconnected);
        room.on("reconnecting", reconnectingUser);
        room.on("reconnected", reconnectedUser);
        room.participants.forEach(participantConnected);
      });
    } 

    return () => {
     // shows video of participant even when canceling the video room where video call is going on
      setRoom(currentRoom => {
        if (currentRoom && currentRoom.localParticipant.state === "connected") {
          currentRoom.localParticipant.tracks.forEach(function(
            trackPublication
          ) {
            trackPublication.track.stop();
          });
          currentRoom.disconnect();
          return null;
        } else {
          return currentRoom;
        }
      });
    };
  }, [roomToJoin, token]);

  const handleAudioToggle = () => {
    room.localParticipant.audioTracks.forEach(track => {
      if (track.track.isEnabled) {
        track.track.disable();
      } else {
        track.track.enable();
      }
      setToggleAudio(!track.track.isEnabled);
    });
  };

  const handleVideoToggle = () => {
    room.localParticipant.videoTracks.forEach(track => {
      if (track.track.isEnabled) {
        track.track.disable();
      } else {
        track.track.enable();
      }
      setToggleVideo(!track.track.isEnabled);
    });
  };

  const remoteParticipants = participants.map(participant => (
    <Participant
      key={participant.sid}
      participant={participant}
      room={room}
      history={history}
      handleAudioToggle={handleAudioToggle}
      handleVideoToggle={handleVideoToggle}
      toggleAudio={toggleAudio}
      toggleVideo={toggleVideo}
    />
  ));


  return (
    <>
      {room ? (
        remoteParticipants.length > 0 ? (
          <VideoRoom
            key={room.localParticipant.sid}
            participant={room.localParticipant}
            remoteParticipants={remoteParticipants}
            room={room}
            history={history}
            handleAudioToggle={handleAudioToggle}
            handleVideoToggle={handleVideoToggle}
            toggleAudio={toggleAudio}
            toggleVideo={toggleVideo}
            prescriptionToggle={prescriptionToggle}
          />
        ) : (
          <LocalPreview
            key={room.localParticipant.sid}
            participant={room.localParticipant}
            remoteParticipants={remoteParticipants}
            room={room}
            history={history}
            handleAudioToggle={handleAudioToggle}
            handleVideoToggle={handleVideoToggle}
            toggleAudio={toggleAudio}
            toggleVideo={toggleVideo}
          />
        )
      ) : (
        ""
      )}
    </>
  );
};
```

**Comment by philnash** [comment]
Hey, thanks for adding to this repo! Could you perhaps send this code as a pull request so that I can review it properly, I'd love to be able to include it once it works as expected too.

As for disabling and enabling tracks, I notice that you are passing your `handleAudioToggle` functions to your remote participants components. Neither [`RemoteVideoTrack`](https://media.twiliocdn.com/sdk/js/video/releases/2.2.0/docs/RemoteVideoTrack.html) or [`RemoteAudioTrack`](https://media.twiliocdn.com/sdk/js/video/releases/2.2.0/docs/RemoteAudioTrack.html) have `disable` or `enable` methods, so you can't mute remote tracks like that. Instead, if you want to mute or stop a remote video for your local participant, you can [detach](https://media.twiliocdn.com/sdk/js/video/releases/2.2.0/docs/RemoteAudioTrack.html#detach__anchor) the remote audio or video track from the DOM.

You should also make sure you listen for [`disabled`](https://media.twiliocdn.com/sdk/js/video/releases/2.2.0/docs/RemoteAudioTrack.html#event:disabled__anchor) and [`enabled`](https://media.twiliocdn.com/sdk/js/video/releases/2.2.0/docs/RemoteAudioTrack.html#event:enabled__anchor) events on your remote participants' tracks so that you can handle that on the local participant's side.

If you can produce a PR that integrates with the existing example app, I'd be happy to try to get it to work with you.

**Comment by Tushant** [comment]
I have this things working. Can I send PR instead?

What I have done is 

1) Send a props called `isLocal` to a participant component so it can show the controls you have used only for the local participants. This should solve your problem i think.

2) Instead of `setToggleAudio(!track.track.isEnabled);`, you have to do `setToggleAudio(track.track.isEnabled);`. This is the issue only on toggling. It has no relation with audio mute/unmute. 

I can send PR so @philnash will have a look at it and improve it if needed.

Thanks

**Comment by philnash** [comment]
I am happy to see any PRs for this application if they are going to help!

**Comment by Tushant** [comment]
Ok I will send the PR then. Do i need any permissions to submit PR?

**Comment by Tushant** [comment]
Here is [PR](https://github.com/philnash/twilio-video-react-hooks/pull/15) you can check

**Comment by philnash** [comment]
Thanks, I will take a look at this tomorrow. 🙂

**Comment by Tushant** [comment]
Thank you.

**Comment by MilanRgm** [comment]
I am still confused on using separate function like `handleAudioToggle` while we have `audioTrack.attach` and `audioTrack.detach` with an event listener `trackSubscribed` and `trackUnSubscribed`

**Comment by umair2k6** [comment]
Hi Phil, I am working on a video chat application and want to switch the camera. I am however able to switch it but only on the remote participant side, the local participant is still showing video from the previous camera. Any suggestions on how to handle this? Thanks.

**Comment by philnash** [comment]
@umair2k6 I would take a look at this repo here which has examples for how to switch cameras in a video chat: https://github.com/philnash/mediadevices-camera-selection

**Comment by Tushant** [comment]
Recently, i saw a post on [validating requests coming from twilio ](https://www.twilio.com/docs/usage/security#validating-requests). I have a little doubt wether it is needed if we are just calling twilio api for starting video call or not. Can you explain me where it is suitable to use?

**Comment by philnash** [comment]
@Tushant validating requests are for when you are receiving data or events from Twilio over webhooks (HTTP requests from Twilio to your server). This is normally used for things like incoming calls and messages with Twilio, so not normally applicable to Video. There are two things you might receive webhooks in Twilio Video for though, [status callbacks for rooms and for video recording compositions](https://www.twilio.com/docs/video/api/status-callbacks). If you're not using those features, then no need to worry about validating requests from Twilio.

**Comment by Tushant** [comment]
By incoming message, do you mean to say when using twilio's sms services?

**Comment by philnash** [comment]
Yeah, an incoming SMS message (or phone call) to a Twilio number triggers a webhook to your application.
