### ISSUE TITLE
Only stream video, not voice

### ISSUE THREAD

**Issue by dat0825** [philnash/twilio-video-react-hooks#2]
Sorry, but when i run this project, only video and not sound. I am sure i turned on my microphone.

**Comment by philnash** [comment]
That's correct, I actually included muting the audio because when testing you don't want to hear the feedback. To remove the mute, remove the `muted={true}` line from [Participant.js](https://github.com/philnash/twilio-video-react-hooks/blob/master/src/Participant.js#L65).

For bonus points, add in a button to toggle muting the audio of a participant.

**Comment by philnash** [comment]
Let me know if this fixes it for you, and we can close this issue?
