### ISSUE TITLE
How do we fix the camera mirror?

### ISSUE THREAD

**Issue by Phyxable** [philnash/twilio-video-react-hooks#20]
When we use the video call, it opens up the camera. But its being mirrored like my left is my right and my right is my left.

**Comment by philnash** [comment]
Most video conferencing applications show your own video in mirrored mode because that is more comfortable when you look at yourself. When it is broadcast it should be the right way around.

This is built into the platform (ie, it's how the browser shows it). If you want to reverse this yourself, you'd have to read the pixels from the video and place them back out onto a canvas the way around you'd want to see them.

That is not something I plan to do as part of this repo, so I'll close this issue for now.

**Comment by Phyxable** [comment]
Ok Can you please show us how to add twilio screen sharing in this repo?
