### ISSUE TITLE
putting local and remote participant video tiles in one row

### ISSUE THREAD

**Issue by Jason-Reich** [philnash/twilio-video-react-hooks#44]
Phil-- Thanks for the great demo repo and blog article "Build a Video Chat with React Hooks"! ...learned a lot.

One quick question: How would I put the local and remote participant video tiles in one row?

I'm familiar with ideas like display: flex and flex-direction: row... but I can't see where to properly place the styling, especially since the .map loop on the remote participant render sort of throws me off (vis-à-vis having typical control over styling).

(Makes no difference to me if the proper solution does or doesn't involve flex/row). Thanks!!!

**Comment by Jason-Reich** [comment]
It looks like putting everything from the Participants.js jsx into the below styled div did the trick:

```
    <div
      style={{
        display: 'inline-block',
      }}
    >
      ...
    </div>
```

**Comment by philnash** [comment]
In the `Room` component the local participant is placed in a different `<div>` to the remote participants. Like this:

```jsx
  return (
    <div className="room">
      <h2>Room: {roomName}</h2>
      <button onClick={handleLogout}>Log out</button>
      <div className="local-participant">
        {room ? (
          <Participant
            key={room.localParticipant.sid}
            participant={room.localParticipant}
          />
        ) : (
          ''
        )}
      </div>
      <h3>Remote Participants</h3>
      <div className="remote-participants">{remoteParticipants}</div>
    </div>
  );
```

The `remote-participants` div is [already using `display: flex`](https://github.com/philnash/twilio-video-react-hooks/blob/master/src/App.css#L103-L108): 

```css
.remote-participants {
  display: flex;
  flex-wrap: nowrap;
  justify-content: space-between;
  padding: 0 2em 2em;
}
```

You could update this to create a `participants` div that contained the local and remote participants, by rendering this in the `Room` component:


```jsx
  return (
    <div className="room">
      <h2>Room: {roomName}</h2>
      <button onClick={handleLogout}>Log out</button>
      <h3>Remote Participants</h3>
      <div className="participants">
        {room ? (
          <Participant
            key={room.localParticipant.sid}
            participant={room.localParticipant}
          />
        ) : (
          ''
        )}
        {remoteParticipants}
      </div>
    </div>
  );
```

This will place the local participant as first in the collection of participants inside that div.

Since I change the name of the `remote-participants` div to `participants` here, you'd want to update the CSS to call it `.participants` too.

```css
.participants {
  display: flex;
  flex-wrap: nowrap;
  justify-content: space-between;
  padding: 0 2em 2em;
}
```

You said you got thrown off by the map over the remote participants.

```jsx
  const remoteParticipants = participants.map(participant => (
    <Participant key={participant.sid} participant={participant} />
  ));
```

What this does is create a variable,  `remoteParticipants`, that is an array of `<Participant>` components for each remote participant in the room. This is then rendered later, originally in the `remote-participants` div:

```jsx
<div className="remote-participants">{remoteParticipants}</div>
```

If there were two remote participants in the room, this would render out to something like:

```jsx
<div className="remote-participants">
  <Participant key={participant[0].sid} participant={participant[0]} />
  <Participant key={participant[1].sid} participant={participant[1]} />
</div>
```

Hope that helps!

**Comment by Jason-Reich** [comment]
@philnash Yup, that all makes sense and it does help (and it works). I had put everything from the Room.js jsx into only one div, and then wrapped the jsx from Participants.js into what I showed above. But what you showed makes more sense and really clarifies how everything is rendering. Thanks...

**Comment by philnash** [comment]
Great to hear it!
