### ISSUE TITLE
why i can't join the room in other device?

### ISSUE THREAD

**Issue by pppaulpeter** [philnash/twilio-video-react-hooks#48]
Hi, 

i am very new to twilio. when i try this demo, i can see the video with http://localhost:3000/, and i also can join the room with another page. But when i try to join the room with my another computer or cellphone(http://192.168.1.145:3000/), it just print out 
16:36:08 ✨ request completed POST 200 /video/token 1ms
16:36:12 ✨ request completed POST 200 /video/token 1ms
16:36:37 ✨ request completed POST 200 /video/token

but in another computer or cellphone i just can't join the room and no error.
![image](https://user-images.githubusercontent.com/24501729/110247381-ec6d2d80-7f63-11eb-8fcb-38dc2268909c.png)

**Comment by philnash** [comment]
I think this is because you are visiting the application over HTTP. The `MediaDevices.getUserMedia()` API, which gets the user's camera and microphone stream, is only available in a secure context, that is, [it is only available over HTTPS](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia#privacy_and_security).

If you need to make your application available to other computers with an HTTPS enabled URL, try [ngrok](https://ngrok.com).

Let me know if this helps at all.

**Comment by pppaulpeter** [comment]
Hi,

thanks for responding. i not mean i want visit it on wlan, i just want to try join the room in LAN. Do i still need use https?

**Comment by philnash** [comment]
You do. The browser does treat localhost as a secure context which is why you can use it locally with no problem. Any IP address, like the one showing in your screenshots, comes under the rules that mean you need HTTPS to use these features. 

These are browser rules, and have nothing to do with the application, there's nothing I can build to change that I'm afraid.

**Comment by pppaulpeter** [comment]
Hi,

I see, thanks. may i ask do you know how to make the example work under https?

**Comment by philnash** [comment]
I don't actually know how to set up HTTPS for your local IP address like you're using it. I use a tool called [ngrok](https://ngrok.com) on the machine that is running the application. It creates a public URL that you can use to visit your application from anywhere. And it comes with HTTPS. I would try using that to see how you get on.

**Comment by pppaulpeter** [comment]
Hi,

it seems the demo here is not support https,right? since it just listen 3000 port as shown in the following image
![image](https://user-images.githubusercontent.com/24501729/110860944-544dac00-82b5-11eb-85bc-572e760eba73.png)
ngrok is a tool to make a service to public, but if the service does't support https, how could make it work? i am sorry i am very new to this.

**Comment by philnash** [comment]
ngrok will forward HTTPS traffic to the HTTP server. It works, I promise, I've used it many times.

**Comment by pppaulpeter** [comment]
Hi,

i have tried that. but it seems it is not working propoerly as shown in the following image.it just complained invalid header. i have also try the http link, it was the same result. Do you know the reason? thanks!
![image](https://user-images.githubusercontent.com/24501729/110936386-b8f61e80-8328-11eb-9cc0-60c350a04fe7.png)

**Comment by philnash** [comment]
Ah, sorry, React expects a bit more. Try running ngrok like this:

```
ngrok http 3000 -host-header="localhost:3000"
```

See this [Stack Overflow question](https://stackoverflow.com/questions/45425721/invalid-host-header-when-ngrok-tries-to-connect-to-react-dev-server) for more detail.

**Comment by pppaulpeter** [comment]
i see, thanks a lot! Have a good weekend

**Comment by pppaulpeter** [comment]
it seems there is no sound in the demo?

**Comment by philnash** [comment]
It's muted to save feedback when testing. Remove the muted attribute here: https://github.com/philnash/twilio-video-react-hooks/blob/master/src/Participant.js#L69

**Comment by philnash** [comment]
I'm going to close this as it seems things are sorted. Feel free to open if you still have issues.

**Comment by pppaulpeter** [comment]
thanks for your help! I am very appricate it. everything works now!
